// app/layout.jsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import './postDetails/sellerProfilecards/SellersProfile.module.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/geomanist" />
      </head>
      <body 
        className="antialiased"
        style={{ fontFamily: "'Geomanist', sans-serif" }}
        suppressHydrationWarning
      >
        <div className="container-fluid m-auto">
          <div className="row">
           
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}