import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "./layout/Header/TopNav";
import Header from "./layout/Header/MainHeader";
import Footer from './layout/Footer/Footer';
import CopyFooter from './layout/Footer/copyright';

import 'bootstrap/dist/css/bootstrap.min.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Added to improve font loading
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // Added to improve font loading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.cdnfonts.com/css/geomanist"
        />
      </head>
      <body 
        className="antialiased"
        style={{ fontFamily: "'Geomanist', sans-serif" }}
        suppressHydrationWarning
      >
        <div className="container-fluid m-auto p-2">
          <div className="row">
            <div className="col-12">
              <TopNav />
            </div>
            <div className="col-12">
              <Header />
            </div>
          </div>
        </div>
        {children}
        <Footer />
        <CopyFooter />
      </body>
    </html>
  );
}
